### PR TITLE
Chore/refactoring repo

### PR DESCRIPTION
**Pull request by lanlugar**
Changed files to TS

### CODE REVIEW

**Comment by lanlugar** [comment]
@Munasco @Sufiyan-dev @athikaf @jonasgodfrey please guys kindly start to review and comment on the new structure of the repository.

**Review by Sufiyan-dev — COMMENTED** [review]
unable to understand folder structure, we need all the app code in single folder and also will be needing contract folder too

**Comment by Sufiyan-dev** [comment]
we need to move all of this into a single folder, so that I can also move my stuff of smart contract into single one

**Comment by lanlugar** [comment]
> we need to move all of this into a single folder, so that I can also move my stuff of smart contract into single one

I have tried to do that, I don't know if you are referencing the new commit, if you are, for sure we can talk about it on the meeting.

**Review by Munasco — APPROVED** [review]

**Review by Sufiyan-dev — APPROVED** [review]
Letsgoooo 🚀

**Pull request merged**
